import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abhishekprabhu
 */
public class f3 extends javax.swing.JFrame {

    
    String dummy;
    
    public f3() {
        initComponents();
    }
    public f3(String dummy)
    {
        initComponents();
        JOptionPane.showMessageDialog(this,"Please fill the form again");
        new f1().setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        register_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        register_username = new javax.swing.JTextField();
        register_email = new javax.swing.JTextField();
        register_address = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        register_password = new javax.swing.JPasswordField();
        register_confirm_password = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        register_gender_male = new javax.swing.JRadioButton();
        register_gender_female = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        register_gender_others = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRATION FORM :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 450, 50));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 66, 70, 20));
        jPanel1.add(register_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 290, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Password :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 30));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Email ;");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, 30));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("Address :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        register_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(register_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 290, -1));

        register_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_emailActionPerformed(evt);
            }
        });
        jPanel1.add(register_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 290, -1));

        register_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_addressActionPerformed(evt);
            }
        });
        jPanel1.add(register_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 290, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Username :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setText("Confirm Password :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 30));

        register_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(register_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 290, -1));
        jPanel1.add(register_confirm_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 290, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("Gender :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        register_gender_male.setText("Male");
        register_gender_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_gender_maleActionPerformed(evt);
            }
        });
        jPanel1.add(register_gender_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        register_gender_female.setText("Female");
        register_gender_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_gender_femaleActionPerformed(evt);
            }
        });
        jPanel1.add(register_gender_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 359, -1, 40));

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, 40));

        register_gender_others.setText("Others");
        register_gender_others.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_gender_othersActionPerformed(evt);
            }
        });
        jPanel1.add(register_gender_others, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 103, 90, 20));

        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plain .jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 566, 471));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void register_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_passwordActionPerformed

    private void register_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_addressActionPerformed

    private void register_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_emailActionPerformed

    private void register_gender_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_gender_maleActionPerformed
        // TODO add your handling code here:
        if(register_gender_male.isSelected())
        {
            register_gender_female.setSelected(false);
            register_gender_others.setSelected(false);
        }
        
        
        
    }//GEN-LAST:event_register_gender_maleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String m = register_name.getText().trim();
            String o = register_password.getText().trim();
            String p = register_email.getText().trim();
            String q = register_address.getText().trim();
            String gender="";
            String b = register_confirm_password.getText().trim();
            String n = register_username.getText().trim();
            
              
            
           if(register_gender_male.isSelected())
           {
                gender = "Male";
            
           }       
           if(register_gender_female.isSelected())
           {
                gender = "Female";
           }
           if(register_gender_others.isSelected())
           {
               gender="Transgender";
           }
           
          
           
           if(m.equals("") ||   o.equals("") ||p.equals("") || q.equals("") || b.equals("") || n.equals("")) 
           {
               JOptionPane.showMessageDialog(null, "TextBox cannot be empty");
           } 
           
            
        //m=name, n=username, o=password, p=email, q=address,
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/ask","abc","abc");
            Statement st = con.createStatement();
            st.execute("insert into registration values('"+m+"','"+o+"','"+p+"','"+q+"','"+gender+"','"+b+"','"+n+"')");
            //JOptionPane.showMessageDialog(this, "Registration successfull");
            
           
            
            
            if(!(o.equals(b)))
           {
               JOptionPane.showMessageDialog(this,"Password Mismatch, Enter the password again");
               register_password.setText("");
               register_confirm_password.setText("");
               f3 f = new f3(dummy);
               //f3.setVisible(true);
               dispose();
           }
            else if(m.equals("") ||  o.equals("") ||p.equals("") || q.equals("") || b.equals("") || n.equals(""))
           {
               JOptionPane.showMessageDialog(null, "TextBox cannot be empty");
           } 
            else{
                JOptionPane.showMessageDialog(this, "Registration successfull");
            }
            
            
    
            
            
            Statement st1 = con.createStatement();
            st1.execute("insert into login values('"+n+"','"+o+"')");//connecting it to f1 form
            st1.execute("insert into orders(username) values('"+n+"')");
            
        }
        catch(Exception e){
            System.out.println("Error: "+e.getMessage());
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new f1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        register_name.setText("");
        register_gender_male.setSelected(false);
        register_gender_female.setSelected(false);
        register_gender_others.setSelected(false);
        register_username.setText("");
        register_password.setText("");
        register_confirm_password.setText("");
        register_email.setText("");
        register_address.setText("");
        reset();
        
    }//GEN-LAST:event_resetActionPerformed

    private void register_gender_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_gender_femaleActionPerformed
        // TODO add your handling code here:
        if(register_gender_female.isSelected())
        {
            register_gender_male.setSelected(false);
            register_gender_others.setSelected(false);
        }
        
    }//GEN-LAST:event_register_gender_femaleActionPerformed

    private void register_gender_othersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_gender_othersActionPerformed
        // TODO add your handling code here:
        if(register_gender_others.isSelected())
        {
            register_gender_male.setSelected(false);
            register_gender_female.setSelected(false);
        }
        
    }//GEN-LAST:event_register_gender_othersActionPerformed

    private void register_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField register_address;
    private javax.swing.JPasswordField register_confirm_password;
    private javax.swing.JTextField register_email;
    private javax.swing.JRadioButton register_gender_female;
    private javax.swing.JRadioButton register_gender_male;
    private javax.swing.JRadioButton register_gender_others;
    private javax.swing.JTextField register_name;
    private javax.swing.JPasswordField register_password;
    private javax.swing.JTextField register_username;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
